export const LOAD_WEB3_SUCCESS = 'LOAD_WEB3_SUCCESS';
export const LOAD_WEB3_FAIL = 'LOAD_WEB3_FAIL';
export const LOAD_BLOCKCHAIN_DATA_SUCCESS = 'LOAD_BLOCKCHAIN_DATA_SUCCESS';
export const LOAD_BLOCKCHAIN_DATA_FAIL = 'LOAD_BLOCKCHAIN_DATA_FAIL';


export const LOAD_MURKIVA_CONTRACT_SUCCESS = 'LOAD_MURKIVA_CONTRACT_SUCCESS';
export const LOAD_MURKIVA_CONTRACT_FAIL = 'LOAD_MURKIVA_CONTRACT_FAIL';
export const LOAD_NFT_TOTALSUPPLY_SUCCESS = 'LOAD_NFT_TOTALSUPPLY_SUCCESS';
export const LOAD_NFT_TOTALSUPPLY_FAIL = 'LOAD_NFT_TOTALSUPPLY_FAIL';
export const LOAD_MURKIVA_NFTS_SUCCESS = 'LOAD_MURKIVA_NFTS_SUCCESS';
export const LOAD_MURKIVA_NFTS_FAIL = 'LOAD_MURKIVA_NFTS_FAIL';

